//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyonEnti.Data2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunMarka
    {
        public int MarkaID { get; set; }
        public int UrunID { get; set; }
        public string MarkaAd { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> AlısFiyat { get; set; }
        public Nullable<decimal> SatısFiyat { get; set; }
        public Nullable<int> StokAdet { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
